#!/usr/bin/env python3
"""Crops the project logo and emits a compact web-sized PNG plus a C byte
array (PROGMEM) for serving from the WiFi portal, matching the pattern used
by pfsense-status-esp32's assets/project_logo_png.h."""
import os
import sys

sys.path.insert(0, os.path.expanduser(
    "/tmp/claude-1000/-home-claudeuser-Projekte/8dbd9bda-fb54-4096-bd88-6e5c3ca19540/scratchpad/pio-venv/lib/python3.13/site-packages"))
from PIL import Image

SRC = os.path.join(os.path.dirname(__file__), "..", "esp_drummachine_logo.png")
OUT_PNG = os.path.join(os.path.dirname(__file__), "..", "tools", "project-logo-320.png")
OUT_H = os.path.join(os.path.dirname(__file__), "..", "include", "assets", "project_logo_png.h")
TARGET_W = 320


def find_content_bbox(img):
    w, h = img.size
    px = img.load()
    minx, miny, maxx, maxy = w, h, 0, 0
    step = 2
    for y in range(0, h, step):
        for x in range(0, w, step):
            r, g, b = px[x, y]
            if not (r > 245 and g > 245 and b > 245):
                minx, maxx = min(minx, x), max(maxx, x)
                miny, maxy = min(miny, y), max(maxy, y)
    pad = 10
    return (max(0, minx - pad), max(0, miny - pad), min(w, maxx + pad), min(h, maxy + pad))


def main():
    img = Image.open(SRC).convert("RGB")
    bbox = find_content_bbox(img)
    img = img.crop(bbox)
    target_h = round(TARGET_W * img.height / img.width)
    img = img.resize((TARGET_W, target_h), Image.LANCZOS)
    # Palette quantization: this artwork (gradients/circuit-board detail)
    # compresses far better as an indexed PNG than true-color - ~110KB vs
    # ~43KB - and 128 colors is plenty for a header logo at this size.
    img = img.convert("P", palette=Image.ADAPTIVE, colors=128)
    img.save(OUT_PNG, optimize=True)

    with open(OUT_PNG, "rb") as f:
        data = f.read()

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    with open(OUT_H, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by tools/convert_logo_web.py from esp_drummachine_logo.png\n")
        f.write("// - served as /project-logo.png by the WiFi portal. Do not hand-edit.\n\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write("const uint8_t kProjectLogoPng[] PROGMEM = {\n")
        for i in range(0, len(data), 20):
            chunk = data[i:i + 20]
            f.write("  " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")
        f.write(f"const size_t kProjectLogoPngLen = {len(data)};\n")

    print(f"web logo: {img.size}, {len(data)} bytes PNG -> {OUT_H}")


if __name__ == "__main__":
    main()
