#!/usr/bin/env python3
"""Crops/shrinks the project logo and emits an LVGL-compatible C image array
(RGB565, LV_IMG_CF_TRUE_COLOR) for the boot/calibration screens."""
import os
import sys

sys.path.insert(0, os.path.expanduser(
    "/tmp/claude-1000/-home-claudeuser-Projekte/8dbd9bda-fb54-4096-bd88-6e5c3ca19540/scratchpad/pio-venv/lib/python3.13/site-packages"))
from PIL import Image

SRC = os.path.join(os.path.dirname(__file__), "..", "esp_drummachine_logo.png")
OUT_H = os.path.join(os.path.dirname(__file__), "..", "include", "logo_image.h")
TARGET_W = 190


def find_content_bbox(img):
    w, h = img.size
    px = img.load()
    minx, miny, maxx, maxy = w, h, 0, 0
    step = 2
    for y in range(0, h, step):
        for x in range(0, w, step):
            r, g, b = px[x, y]
            if not (r > 245 and g > 245 and b > 245):
                minx, maxx = min(minx, x), max(maxx, x)
                miny, maxy = min(miny, y), max(maxy, y)
    pad = 10
    return (max(0, minx - pad), max(0, miny - pad), min(w, maxx + pad), min(h, maxy + pad))


def main():
    img = Image.open(SRC).convert("RGB")
    bbox = find_content_bbox(img)
    img = img.crop(bbox)

    target_h = round(TARGET_W * img.height / img.width)
    img = img.resize((TARGET_W, target_h), Image.LANCZOS)

    w, h = img.size
    px = img.load()
    out_bytes = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out_bytes.append(rgb565 & 0xFF)
            out_bytes.append((rgb565 >> 8) & 0xFF)

    with open(OUT_H, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by tools/convert_logo.py from esp_drummachine_logo.png\n")
        f.write("// - do not hand-edit.\n\n")
        f.write("#include <lvgl.h>\n\n")
        f.write(f"#define LOGO_WIDTH {w}\n")
        f.write(f"#define LOGO_HEIGHT {h}\n\n")
        f.write(f"static const uint8_t logo_map[] = {{\n")
        for i in range(0, len(out_bytes), 16):
            chunk = out_bytes[i:i + 16]
            f.write("  " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("static const lv_img_dsc_t logo_desc = {\n")
        f.write("  .header = {\n")
        f.write("    .cf = LV_IMG_CF_TRUE_COLOR,\n")
        f.write("    .always_zero = 0,\n")
        f.write("    .reserved = 0,\n")
        f.write("    .w = LOGO_WIDTH,\n")
        f.write("    .h = LOGO_HEIGHT,\n")
        f.write("  },\n")
        f.write("  .data_size = sizeof(logo_map),\n")
        f.write("  .data = logo_map,\n")
        f.write("};\n")

    print(f"logo: {w}x{h}, {len(out_bytes)} bytes raw -> {OUT_H}")


if __name__ == "__main__":
    main()
